CREATE TABLE [dbo].[InfoCheckList] (
    [Id]                                                 BIGINT         IDENTITY (1, 1) NOT NULL,
    [UserId]                                             BIGINT         NOT NULL,
    [DateAnswered]                                       DATETIME2 (7)  NOT NULL,
    [FirstName]                                          NVARCHAR (256) NOT NULL,
    [Surname]                                            NVARCHAR (256) NOT NULL,
    [Gender]                                             NVARCHAR (MAX) DEFAULT (N'') NOT NULL,
    [PreferredPronoun]                                   NVARCHAR (256) NOT NULL,
    [DateOfBirth]                                        DATETIME2 (7)  NOT NULL,
    [AgeNow]                                             INT            NOT NULL,
    [Address]                                            NVARCHAR (256) NOT NULL,
    [TelephoneNumber]                                    NVARCHAR (256) NOT NULL,
    [Email]                                              NVARCHAR (256) NOT NULL,
    [UniversityName]                                     NVARCHAR (256) NOT NULL,
    [NameOfQualification]                                NVARCHAR (256) NOT NULL,
    [CourseStartDate]                                    DATETIME2 (7)  NOT NULL,
    [CourseEndDate]                                      DATETIME2 (7)  NOT NULL,
    [StudentFromUkOrOverseas]                            NVARCHAR (256) NOT NULL,
    [PreferredLanguage]                                  NVARCHAR (256) NOT NULL,
    [DateOfLastEyeTest]                                  DATETIME2 (7)  NOT NULL,
    [WearGlassesLenses]                                  NVARCHAR (MAX) NULL,
    [PrescribedTintedLens]                               NVARCHAR (MAX) NULL,
    [DateOfLastHearingTest]                              DATETIME2 (7)  NOT NULL,
    [AnyHearingDifficulties]                             NVARCHAR (MAX) NOT NULL,
    [AnySeriousMedicalConditionsInThePast]               NVARCHAR (MAX) NOT NULL,
    [AreYouCurrentlyHealthy]                             NVARCHAR (MAX) NOT NULL,
    [AnyMentalHealtDifficulties]                         NVARCHAR (MAX) NOT NULL,
    [WereYouLateLearningToTalk]                          NVARCHAR (MAX) NOT NULL,
    [HadSpeechTherapies]                                 NVARCHAR (MAX) NOT NULL,
    [DifficultToSayAnySounds]                            NVARCHAR (MAX) NOT NULL,
    [DoYouHardPronounceWordsNow]                         NVARCHAR (MAX) NOT NULL,
    [CanExpressIdeasFluently]                            NVARCHAR (MAX) NOT NULL,
    [LearnSkillsWalkingRunning]                          NVARCHAR (MAX) NOT NULL,
    [CanSwimAndRideBicycle]                              NVARCHAR (MAX) NOT NULL,
    [AnySportActivitiesNow]                              NVARCHAR (MAX) NOT NULL,
    [ClumsyAsAChild]                                     NVARCHAR (MAX) NOT NULL,
    [SkillsUsingYourHands]                               NVARCHAR (MAX) NOT NULL,
    [FindEasyToDevelopNeatHandwriting]                   NVARCHAR (MAX) NOT NULL,
    [ReceivedAnyPreviousAssesments]                      NVARCHAR (MAX) NOT NULL,
    [CloseFamilyMembersWithLearningDifferences]          NVARCHAR (MAX) NOT NULL,
    [CloseFamilyMembersWithDifficultyDevelopingLiteracy] NVARCHAR (MAX) NOT NULL,
    [HaveAlwaysLivedInUK]                                NVARCHAR (MAX) NOT NULL,
    [IsEnglishEverydayLanguage]                          NVARCHAR (MAX) NOT NULL,
    [RegularySpeakAnyOtherLanguage]                      NVARCHAR (MAX) NOT NULL,
    [WereSchoolLessionsInEnglish]                        NVARCHAR (MAX) NOT NULL,
    [FindEasyToReadWriteOtherLanguages]                  NVARCHAR (MAX) NOT NULL,
    [EnjoyGoingToSchool]                                 NVARCHAR (MAX) NOT NULL,
    [FavouriteSubjects]                                  NVARCHAR (MAX) NOT NULL,
    [HowDidYouFindLearningToRead]                        NVARCHAR (MAX) NOT NULL,
    [HowDidYouGetRememberingWhatRead]                    NVARCHAR (MAX) NOT NULL,
    [HowDidFindLearningToSpell]                          NVARCHAR (MAX) NOT NULL,
    [HowDidFindWritingEssays]                            NVARCHAR (MAX) NOT NULL,
    [HowDidOnDevelopingNumeracySkills]                   NVARCHAR (MAX) NOT NULL,
    [HardToCompleteExaminationsInTime]                   NVARCHAR (MAX) NOT NULL,
    [DidYouHaveSSEN]                                     NVARCHAR (MAX) NOT NULL,
    [AttendSchoolRegularly]                              NVARCHAR (MAX) NOT NULL,
    [AnyProlongedPeriodsOfAbsence]                       NVARCHAR (MAX) NOT NULL,
    [DidChangedSchoolsOften]                             NVARCHAR (MAX) NOT NULL,
    [ResultsOfALevelExaminations]                        NVARCHAR (MAX) NOT NULL,
    [JobsDone]                                           NVARCHAR (MAX) NOT NULL,
    [WhatEnjoyedOnJobsDone]                              NVARCHAR (MAX) NOT NULL,
    [WhyHaveRequestedAssesment]                          NVARCHAR (MAX) NOT NULL,
    [YourStrengthsAsPerson]                              NVARCHAR (MAX) NOT NULL,
    [CurrentStrengthsWithReading]                        NVARCHAR (MAX) NOT NULL,
    [CurrentStrengthsWithTasksAsPlanning]                NVARCHAR (MAX) NOT NULL,
    [CurrentStrengthsWithMemory]                         NVARCHAR (MAX) NOT NULL,
    [CurrentStrengthsWithSocialInteraction]              NVARCHAR (MAX) NOT NULL,
    [CurrentStrengthsWithNumeracy]                       NVARCHAR (MAX) NOT NULL,
    [DriveACar]                                          NVARCHAR (MAX) NOT NULL,
    [FreeTimeActivities]                                 NVARCHAR (MAX) NOT NULL,
    [HeadachesReading]                                   NVARCHAR (MAX) NOT NULL,
    [ReadingSoreEyes]                                    NVARCHAR (MAX) NOT NULL,
    [ReadingTired]                                       NVARCHAR (MAX) NOT NULL,
    [DistractedWhenReading]                              NVARCHAR (MAX) NOT NULL,
    [LessComfortableLongerReading]                       NVARCHAR (MAX) NOT NULL,
    [PrefferDimLights]                                   NVARCHAR (MAX) NOT NULL,
    [ReadingFromWhitePaperBright]                        NVARCHAR (MAX) NOT NULL,
    [ReadingFromWhitePageFormsPatterns]                  NVARCHAR (MAX) NOT NULL,
    [DoesBackgorundShimmer]                              NVARCHAR (MAX) NOT NULL,
    [DoesPrintApoearJitter]                              NVARCHAR (MAX) NOT NULL,
    [ScrewEyesWhenReading]                               NVARCHAR (MAX) NOT NULL,
    [RubEyesWhenReading]                                 NVARCHAR (MAX) NOT NULL,
    [UseMarkerOrFingerWhenReading]                       NVARCHAR (MAX) NOT NULL,
    [CoverOneEyeWhenReading]                             NVARCHAR (MAX) NOT NULL,
    [LosePlaceWHenReading]                               NVARCHAR (MAX) NOT NULL,
    [RereadOrSkipWhenReading]                            NVARCHAR (MAX) NOT NULL,
    [TextBlurredWhenReading]                             NVARCHAR (MAX) NOT NULL,
    [DistanceObjectsBlurred]                             NVARCHAR (MAX) NOT NULL,
    [DoubleWordsWhenReading]                             NVARCHAR (MAX) NOT NULL,
    [AdditionalInformation]                              NVARCHAR (MAX) NOT NULL,
    [MoveEyesAndBlinkWhenReading]                        NVARCHAR (MAX) DEFAULT (N'') NOT NULL,
    CONSTRAINT [PK_InfoCheckList] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InfoCheckList_AbpUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [dbo].[AbpUsers] ([Id]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_InfoCheckList_UserId]
    ON [dbo].[InfoCheckList]([UserId] ASC);

